# Generated by Django 6.0.4 on 2026-05-11 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmovement',
            old_name='Product',
            new_name='product',
        ),
    ]
